trigger:
  branches:
    include:
    - master
variables:
- name: azureSubscription
  value: 'YAML_Pipelines'
- name: WebAppKind
  value: 'Web App on Linux'
- name: WebAppName
  value: aj-webapp-yaml
stages:
- stage: Build stage
  jobs:
  - job: Build and publish .war artifact
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    - task: CopyFiles@2
      inputs:
        Contents: '**/*.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'warfile'
        publishLocation: 'Container'
- stage: Deployment stage 
  jobs:
  - job: Deploy to QA & TestAutomation
    pool:
      vmImage: windows-latest
    steps:
    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy to QA'
      inputs:
        azureSubscription: $(azureSubscription)
        appType: $(appType)
        WebAppName: $(WebAppName)
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.war'
        StartupCommand: '$(Parameters.StartupCommand)'
    - task: CmdLine@2
      displayName: 'Clone TestAutomation repo'
      inputs:
        script: |
          echo ===starting the script===
          echo ===upgrading the OS===
          sudo apt-get update
          echo ===OS upgrade done===
          echo ===install git===
          sudo apt-get install git
          which git
          echo ===git installation completed===
          echo ===list files in pipeline root folder===
          ls
          echo ===list files in pipeline root folder done===
          echo ===pwd===
          pwd
          echo ===pwd completed
          echo ===cloning the repo to the pipeline root folder===
          git clone https://github.com/ajderu/TestAutomation.git
          echo ===repo cloning completed==
          echo ===pwd===
          pwd
          echo ===pwd completed
          echo ====cd TestAutomation===
          cd TestAutomation
          echo ====cd TestAutomation done===
          echo ===pwd===
          pwd
          echo ===pwd completed
          echo ===ls===
          ls
          echo ===ls output completed
          echo ===script ended===
    - task: CopyFiles@2
      displayName: 'Copy TestAutomation repo to a'
      inputs:
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    #a is $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      displayName: 'Publish TestAutomation repo artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/TestAutomation'
        ArtifactName: 'TestAutomation'
        publishLocation: 'Container'
    - task: Maven@4
      displayName: 'Run TestAutomation'
      inputs:
        mavenPomFile: '$(Build.ArtifactStagingDirectory)/TestAutomation/pom.xml'
        goals: test