trigger:
  branches:
    include:
    - master
    
variables:
- name: azureSubscription
  value: 'YAML_Pipelines'
  #this is the service connection to MS Azure
- name: WebAppNameQA
  value: aj-webapp-qa
  #under App Service in MS Azure I created the aj-webapp-qa webapp
- name: WebAppNameProd
  value: aj-webapp-production
  #under App Service in MS Azure I created the aj-webapp-production webapp
- name: appType
  value: 'Web App on Linux'
  
stages:

- stage: _BuildStage
  jobs:
  - job: Build
    pool:
      vmImage: windows-latest
    steps:
    - task: Maven@3
      displayName: 'Generating .war file'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    - task: CopyFiles@2
      displayName: 'Copy .war file to a'
      inputs:
        Contents: '**/*.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish .war file to a folder'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'warfile'
        publishLocation: 'Container'
        
- stage: _DeployQAStage
  jobs:
  - job: DeployQA
    pool:
      vmImage: windows-latest
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download warfile build artifact'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'warfile'
        downloadPath: '$(Build.ArtifactStagingDirectory)'/**/*.war'
        StartupCommand: '$(Parameters.StartupCommand)'
    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy QA'
      inputs:
        azureSubscription: $(azureSubscription)
        WebAppName: $(WebAppNameQA)
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.war'
        StartupCommand: '$(Parameters.StartupCommand)'
    - task: CmdLine@2
      displayName: 'TestAutomation - Clone the https://github.com/ajderu/TestAutomation.git repo'
      inputs:
        script: |
          echo ===starting the script===
          echo ===upgrading the OS===
          sudo apt-get update
          echo ===OS upgrade done===
          echo ===install git===
          sudo apt-get install git
          which git
          echo ===git installation completed===
          echo ===list files in pipeline root folder===
          ls
          echo ===list files in pipeline root folder done===
          echo ===pwd===
          pwd
          echo ===pwd completed
          echo ===cloning the repo to the pipeline root folder===
          git clone https://github.com/ajderu/TestAutomation.git
          echo ===repo cloning completed==
          echo ===pwd===
          pwd
          echo ===pwd completed
          echo ====cd TestAutomation===
          cd TestAutomation
          echo ====cd TestAutomation done===
          echo ===pwd===
          pwd
          echo ===pwd completed
          echo ===ls===
          ls
          echo ===ls output completed
          echo ===script ended===
    - task: CopyFiles@2
      displayName: 'TestAutomation - Copy TestAutomation repo to a folder'
      inputs:
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'TestAutomation - Publish TestAutomation repo artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/TestAutomation'
        ArtifactName: 'TestAutomation'
        publishLocation: 'Container'
    - task: Maven@4
      displayName: 'Run TestAutomation'
      inputs:
        mavenPomFile: '$(Build.ArtifactStagingDirectory)/TestAutomation/pom.xml'
        goals: test
    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy to Prod'
      inputs:
        azureSubscription: $(azureSubscription)
        appType: $(appType)
        WebAppName: $(WebAppNameProd)
        packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.war'
        StartupCommand: '$(Parameters.StartupCommand)'


