# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# cross check CI
trigger:
- master

pool:
  vmImage: ubuntu-latest

variables: 
- name: ConnectedServiceName
  value: e41dbaa4-dee2-46f5-af6a-474e47050169
- name: WebAppKind
  value: 'Web App on Linux'
- name: WebAppName
  value: aj-webapp-demo

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warfile'
    publishLocation: 'Container'
- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure App Service'
  inputs:
    azureSubscription: $ConnectedServiceName
    appType: '$WebAppKind'
    WebAppName: '$WebAppName'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.war'
    StartupCommand: '$(Parameters.StartupCommand)'